### ISSUE TITLE
error starting MaintenanceVM GemServer

### ISSUE THREAD

**Issue by HeSe** [dalehenrich/gsApplicationTools#11]
Based on the ZnSeasideNewGemServer implementation I implemented my own non-seaside MaintenanceGemServer. Unfortunately I run into this error:

topaz 1> topaz 1> topaz 1> topaz 1> GemStone Smalltalk Compiler Errors:
   (GemServerRegistry gemServerNamed: 'OtfaMaintenanceVM') scriptStartServiceOn: instance.
 *                                                                               ^1

1: [1031] undefined symbol
topaz > exec iferr 1 : stack
Stack is not active
topaz 1> topaz 1> topaz 1> topaz 1> GemStone Smalltalk Compiler Errors:
   | logEntry |
   System beginTransaction.
   (logEntry := ObjectLogEntry
     fatal: 'OtfaMaintenanceVM_server_instance: topaz exit'
     object:
       'pid: ', (System gemVersionReport at: 'processId') printString) addToLog.
   (GemServerRegistry gemServerNamed: 'OtfaMaintenanceVM')
     ifNotNil: [:gemServer | gemServer crashLog add: (instance) asString -> logEntry ].
 *                                                    ^1
   System commitTransaction.

1: [1031] undefined symbol
topaz > exec iferr 1 : stack
Stack is not active

Do I understand it right, that one needs to also define a port for a maintenanceGemserver?

**Comment by HeSe** [comment]
The Port parameter needs to be in string format since the default port of the MaintenanceVM ist defined as 'instance'. I'll provide a fix

**Comment by dalehenrich** [comment]
Yeah, the port can be anything as it is not used ... this is probably 
something that can be eventually improved ...

Dale

**Comment by HeSe** [comment]
Hi Dale,

I have trouble with Jade and filetree here.

I want to provide a fix in zinc and can't export the changes.

I need to change basicServerOn: port in ZnNewGemServer to:
----------------------------------------------------
basicServerOn: port
   "forked by caller"

   | znServer |
   znServer := self serverInstance.
   znServer port: port asInteger.
   znServer initializeServerSocket.
   [
   [
   self
     gemServer: [
       znServer serverSocket isValid
         ifTrue: [ znServer serveConnectionsOn: znServer serverSocket ] ]
     beforeUnwind: [ :ex | ex pass ] ]
     repeat ]
     ifCurtailed: [ znServer releaseServerSocket ]
-----------------------------------------------------


Could I also do this change directly in GitHub or does do I screw up 
filetree versioning this way?

This fix is part of this issue: 
https://github.com/dalehenrich/gsApplicationTools/issues/11


Thanks
Sebastian




Am 30.03.2015 um 09:36 schrieb Dale Henrichs:

**Comment by dalehenrich** [comment]
Sebastian,

I'm looking at this change and I don't think that adding the 
beforeUnwind: has any effect ... by default the exception is passed. The 
only reason that you'd use a beforeUnwind: block is that you wanted to 
handle an exception specially ...

Also I'm interesed in the use case for asInteger ... the port is 
supposed to be an integer in the first place ... I don't think that I 
want to allow folks to be passing around strings or floats as the port 
number ... at least I don't _think_ I want to do that ...

Dale

**Comment by HeSe** [comment]
Hi Dale,

when you register a Maintenace gem then this is done e.g. like this

  MaintenanceVmGemServer register: 'myMaintenanceServerVM'

then this Gemserver will use it's default port

defaultPortOrResourceNameList
   "no ports for maintenance vm ... single instance of maintenance 
should be launched"

   ^ #('instance')

This is a string.

So once the we start this gem the compile error provided in the script 
startGemServerGem occurs.
This is due to the fact that the string "instance" is considered a 
undeclared temporary or instance variable during the compile process.

This is why I changed the script. But this leads to the problem that now 
the PORT is sent as a String to the startup routine "basicServerOn:".
This is why I added the asInteger ,....

But this only work for this particular GemServer. I think the other 
implementors of basicServerOn: need also be changed.
I am not using Seaside and did jsut find out about that fact...
I assume there are some more implementations out there...

I assume it might be best to change the startGemServerGem script so that 
it can handle both. String and Integer.

Sebastian




Am 01.04.2015 um 15:00 schrieb Dale Henrichs:

**Comment by dalehenrich** [comment]
Yeah, I guess for me the root problem is that the string 'instance' is 
used .... asInteger presumably doesn't fix the 'instance' guy unless it 
does something like return 0 ... in which case the defalut port number 
should be 0 ...

if this works for you, then continue to use it, but I will probably want 
to solve the issue differently ...

Dale

**Comment by dalehenrich** [comment]
@HeSe I'm going to move this issue to GsDevKit/gsApplicationTools ... where it belongs and then turn off issues here ... I was quite confused about this when I didn't see anything over at GsDevKit/gsApplicationTools:)

**Comment by dalehenrich** [comment]
discussion moved to https://github.com/GsDevKit/gsApplicationTools/issues/30

**Comment by HeSe** [comment]
No worries, the 32Bit prereqs were wrong. I did an upgrade from 12.04 to 
14.04 and didn't update the gsDEvKit prerequs, yet...
Now it is fine.


Sorry
Sebastian

-------- Weitergeleitete Nachricht --------
Betreff: 	Fwd: Re: [Glass] GsDevKit Server Blocks for Thin Client 
appications ... pre-announcement
Datum: 	Mon, 20 Apr 2015 11:06:45 -0700
Von: 	Sebastian Heidbrink <sebastian_heidbrink@yahoo.de>
An: 	dale henrichs <dale.henrichs@gemtalksystems.com>



Okay,

Now with the ssh-keys I tried to install the whole new roassal branch 
server and client according to the Roassal script at [1]

And I endup with as missing ssh plugin :-D

ZdcPluginMissing: SSL/TLS plugin initailization failed (VM plugin 
missing ? OS libraries missing ?)


Heres the log

    GsDevKit script: createTodeImage
=================
create todeClient image using 
/home/sheidbrink/Documents/gsDevKitHome/tode/sys/local/pharo/todeLoad.st
ioLoadModule(/home/sheidbrink/Documents/gsDevKitHome/pharo/pharo-vm/libSqueakSSL.so):
   libssl.so.1.0.0: cannot open shared object file: No such file or 
directory

...RETRY->BaselineOfMetacello
...RETRY->BaselineOfMetacello'Errors in script loaded from 
/home/sheidbrink/Documents/gsDevKitHome/tode/sys/local/pharo/todeLoad.st'
ZdcPluginMissing: SSL/TLS plugin initailization failed (VM plugin 
missing ? OS libraries missing ?)
ZdcPluginSSLSession>>initialize in Block: [ :exception | ...
BlockClosure>>cull:
MethodContext(ContextPart)>>handleSignal: in Block: [ self 
exceptionHandlerBlock cull: exception ]
BlockClosure>>ensure:
MethodContext(ContextPart)>>handleSignal:
PrimitiveFailed(Exception)>>signal
PrimitiveFailed class(SelectorException class)>>signalFor:
ZdcPluginSSLSession(Object)>>primitiveFailed:
ZdcPluginSSLSession(Object)>>primitiveFailed
ZdcPluginSSLSession>>primitiveSSLCreate
ZdcPluginSSLSession>>initialize in Block: [ handle := self 
primitiveSSLCreate ]
BlockClosure>>on:do:
ZdcPluginSSLSession>>initialize
ZdcPluginSSLSession class(Behavior)>>new
ZdcSecureSocketStream>>sslSession
ZdcSecureSocketStream>>connect
ZnNetworkingUtils>>socketStreamToUrlDirectly:
ZnNetworkingUtils>>socketStreamToUrl:
ZnNetworkingUtils class>>socketStreamToUrl:
ZnClient>>getConnectionAndExecute
ZnClient>>executeWithRedirectsRemaining:
ZnClient>>executeWithRetriesRemaining: in Block: [ self 
executeWithRedirectsRemaining: self maxNumb...etc...
BlockClosure>>on:do:
ZnClient>>executeWithRetriesRemaining:
ZnClient>>executeWithTimeout in Block: [ self 
executeWithRetriesRemaining: self numberOfR...etc...
BlockClosure>>on:do:
ZnClient>>executeWithTimeout in Block: [ ...
ZnClient>>withTimeoutDo: in Block: [ ^ block value ]
ZnConnectionTimeout(DynamicVariable)>>value:during: in Block: [ ...
BlockClosure>>ensure:



Sebastian




-------- Weitergeleitete Nachricht --------
Betreff: 	Re: [Glass] GsDevKit Server Blocks for Thin Client appications 
... pre-announcement
Datum: 	Mon, 20 Apr 2015 09:51:23 -0700
Von: 	Sebastian Heidbrink <sebastian_heidbrink@yahoo.de>
An: 	Dale Henrichs <dale.henrichs@gemtalksystems.com>



I get access right issues following your scripts at [1].
I am on Ubuntu now.

Sebastian





[1] 
https://github.com/GsDevKit/gsDevKitHome/blob/dev/projects/roassal/devBootstrap.md#roassal-visualization-setup-and-install


Am 18.04.2015 um 20:54 schrieb Dale Henrichs via Glass:
> Sebastian,
>
> Follow these directions to do use the server blocks install[1] ... for 
> best results right now follow all of the steps with a fresh clone so 
> you'll get the right checkout of gsDevKitHome and tODE ... the 
> standard installs are written to work with the master branches, but 
> both projects are in development ... part of the installation 
> instructions arrange for you to load the dev branch of tode in both 
> pharo and gemstone...
>
> Dale
>

[1] 
https://github.com/GsDevKit/gsDevKitHome/blob/dev/projects/roassal/devBootstrap.md#roassal-visualization-setup-and-install 

>
> On 4/18/15 6:51 PM, Sebastian Heidbrink via Glass wrote:
>> Hi Dale,
>>
>> which are the branches on has to load in order to get this package in 
>> a tODE image?
>>
>> I am missing he TDShell forSessionNamed: method.
>>
>> Am I right that this would be the implementation?
>> TDShell class >>
>> forSessionNamed: aSessionName
>>   ^ self sessionDescription: (TDSessionDescription importFrom: self 
>> sessionDescriptionHome, aSessionName)
>>
>> Cheers
>> Sebastian
>>
>>
>> On 2015-04-15 10:23 PM, Dale Henrichs via Glass wrote:
>>> A GsDevKit Server Block[1] is a block that is written in-line in 
>>> client Smalltalk, but is executed in GemStone. For example the 
>>> following expression is executed in a standard Pharo workspace:
>>>
>>>   | shell x y |
>>>   shell := TDShell forSessionNamed: 'devKit'.
>>>   x := 3.
>>>   y := 4.
>>>   shell onServerDo: [ x + y ].
>>>
>>> and the `[3 + 4 ]` block is executed in GemStone using the `devKit` 
>>> session description to log into the stone. The temp vars x and y 
>>> referenced in the server block and defined in Pharo are shipped 
>>> across the wire to GemStone along with block source where the block 
>>> source is compiled and executed. The result is then shipped back 
>>> across the wire and returned as the result of #onServerDo: message 
>>> in Pharo. Pharo execution can continue on using the result. STON[2] 
>>> is used to serialize the objects that are shipped across the wire.
>>>
>>> For any of you familiar with underpinnings of GemTools, Jade or 
>>> tODE, this is not necessarily ground-breaking technology, however, 
>>> exposing this capability to developers just may be.
>>>
>>> It has been a long standing crime that developers in the Pharo 
>>> community choose to use  MongoDB and MySQL over GemStone, but 
>>> frankly the problem is that (until now) we have not had a simple 
>>> client-based solution for adding GemStone-based persistence for 
>>> native Pharo applications - the pharo developers have not really had 
>>> a choice.
>>>
>>> Being able to embed server blocks in client code certainly qualifies 
>>> as simple. Solution(?), well that remains to be seen, but I am 
>>> optimistic.
>>>
>>> As a more concrete example, here's Pharo workspace code that uses 
>>> NeoCSV running in Pharo to load stone objects in a Dictionary in 
>>> GemStone:
>>>
>>>   'NeoCSVBenchmark.csv' asFileReference
>>>   readStreamDo: [ :stream |
>>>   | reader converter buffer bufCnt numRecords records |
>>>   converter := [ :string | NeoNumberParser parse: string ].
>>>   reader := NeoCSVReader on: (ZnBufferedReadStream on: stream).
>>>   reader
>>>     recordClass: NeoCSVTestObject;
>>>     addIntegerField: #'x:';
>>>     addIntegerField: #'y:';
>>>     addIntegerField: #'z:'.
>>>   buffer := Array new: 1000.
>>>   bufCnt := 0.
>>>   [ reader atEnd ]
>>>     whileFalse: [
>>>       bufCnt := bufCnt + 1.
>>>       buffer at: bufCnt put: reader next.
>>>       bufCnt = buffer size
>>>         ifTrue: [
>>>           numRecords := bufCnt.
>>>           records := buffer.
>>>           DevKitShell
>>>             onServerDo: [
>>>               1 to: numRecords do: [ :index |
>>>                 | record |
>>>                 record := records at: index.
>>>                 NeoCSVDictionary at: record x put: record ].
>>>               System commitTransaction.
>>>               nil ].
>>>           bufCnt := 0 ] ] ].
>>>    DevKitShell onServerDo: [ System commitTransaction ]
>>>
>>> The code ships 1000 instances of NeoCSVTestObject at a pop to 
>>> GemStone. Using the above technique, one can easily arrange to store 
>>> some pretty large object graphs in GemStone ... Efficient queries 
>>> based on standard Smalltalk can be written on the client and 
>>> transparently performed in GemStone (see the GsDevKitServerBlocks 
>>> doc[1] for the complete example).
>>>
>>> Server blocks do not duplicate the functionality GemBuilder for 
>>> Smalltalk[6][7] which provides transparent replication and 
>>> maintenance of objects between the client and server. With server 
>>> blocks you end up with disconnected copies of server objects.
>>>
>>> Because of this disconnect, I think the best way to architect an 
>>> application using server blocks, is to plan on "executing all 
>>> business logic" on the server --- If you are using an MVC pattern, 
>>> the M would primarily be managed on the server while the VC would be 
>>> managed on the client.
>>>
>>> As an application evolves, the code can migrate back and forth 
>>> between client and server as needed.
>>>
>>> Most of the server blocks code leverages tODE and has been in use 
>>> for several years. The code that spelunks in the block structure and 
>>> extracts the _value_ of temp variables is only a couple of days old 
>>> and has some pretty rough edges (notice the odd placement of temp 
>>> variables and declarations in the above example).
>>>
>>> The server-side debugger and inspectors, etc. will use tODE (at 
>>> least for now) ...  in the server blocks doc[1] I demonstrate an 
>>> #exportClassToServer: to illustrate the potential to share code in 
>>> weird and wonderful ways between the client and server.
>>>
>>> If you have the interest/opportunity to take this code for a spin, 
>>> let me know. I have written instructions[5] for installing the 
>>> experimental Roassal Visualization code[4] (GemStone and Pharo3.0 or 
>>> Pharo4.0) for Pierre Chanson and those instructions can be used for 
>>> doing work with GsDevKit
>>> Server Blocks. There are a handful of obvious things that need to be 
>>> done:
>>>   - connection pools
>>>   - coordinated client/server debuggers
>>>   - client-side exception handlers for server errors
>>>   - more???
>>> and if folks express interest in start to do exploratory work with 
>>> server blocks, then I will make time to provide support.
>>>
>>> I am hoping to have something to announce by Smalltalks in 
>>> November,so it would be useful if some experienced GemStoners tried 
>>> things out before then...
>>>
>>> I do have to finish up the documentation for GsDevKitHome 1.0.0 and 
>>> tODE 0.1.0 and I'm also committed to doing some work on the 3.3 
>>> GemStone release, so we'll see how that goes:)
>>>
>>> I also think that server blocks can be very useful for the "develop 
>>> in Pharo, deploy in GemSstone" crowd, since it will be possible to 
>>> write "pharo-based scripts" to perform server-side tasks ...
>>>
>>> Questions or comments?
>>>
>>> Dale
>>>
>>> [1] 
>>> https://github.com/GsDevKit/gsDevKitHome/blob/dev/docs/articles/gsDevKitServerBlocks.md#gsdevkit-server-blocks
>>> [2] https://github.com/GsDevKit/ston#ston---smalltalk-object-notation
>>> [3] https://vimeo.com/123261640
>>> [4] 
>>> https://github.com/GsDevKit/gsDevKitHome/tree/dev/projects/roassal#roassal-visualization
>>> [5] 
>>> https://github.com/GsDevKit/gsDevKitHome/blob/dev/projects/roassal/devBootstrap.md
>>> [6] http://gemtalksystems.com/products/gbs-vw/
>>> [7] http://gemtalksystems.com/products/gbs-va/
>>>
>>>
>>> _______________________________________________
>>> Glass mailing list
>>> Glass@lists.gemtalksystems.com
>>> http://lists.gemtalksystems.com/mailman/listinfo/glass
>>
>>
>>
>> _______________________________________________
>> Glass mailing list
>> Glass@lists.gemtalksystems.com
>> http://lists.gemtalksystems.com/mailman/listinfo/glass
>
>
>
> _______________________________________________
> Glass mailing list
> Glass@lists.gemtalksystems.com
> http://lists.gemtalksystems.com/mailman/listinfo/glass
